# Don't print a new line at the start of the prompt
add_newline = false

# Make prompt a single line instead of two lines
[line_break]
disabled = true

# Replace the "â¯" symbol in the prompt with "âœ" âœ— î˜« â®
# [character]
# success_symbol = "[\\$](green)"
# error_symbol = "[âœ— \\$](#bf616a)"
# vicmd_symbol = "[î˜« \\$](#5e81ac)"

[directory]
# format = "[$path$read_only[\\]](#bf616a)](182)($read_only_style)"
truncation_length = 1
# truncation_symbol = "â€¦/"
read_only = " ğŸ”’" 

[git_branch]
symbol = "ï˜ "
