# Don't print a new line at the start of the prompt
add_newline = false

# Make prompt a single line instead of two lines
[line_break]
disabled = true

# Replace the "â¯" symbol in the prompt with "âœ" âœ— î˜« â®
[character]
success_symbol = "[\\$](white)"
error_symbol = "[\\$](#bf616a)"
vicmd_symbol = "[\\$](cyan)"

[directory]
format = "[$path$read_only ](purple)"
truncation_symbol = "â€¦/"
read_only = " ğŸ”’" 

[git_branch]
format = "on [$symbol$branch(:$remote_branch)](bold cyan) "
symbol = "ï˜ "

[cmd_duration]
disabled = true

[lua]
symbol = "î˜  "

[python]
symbol = "ï Ÿ "

[rlang]
symbol = "R "

[conda]
ignore_base = false

[git_status]
staged = "[ï‘${count}](green)"
modified = "[!${count}](yellow)"
ahead = "[î“${count}](cyan)"
behind = "î€${count}"
untracked = "[?${count}](white)"
deleted = "âœ˜${count}"
